name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # See https://github.com/helm/chart-releaser-action/issues/6
      - name: Install Helm
        run: |
          curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm init --client-only

      - name: Add dependency chart repos
        run: |
          helm repo add stable https://kubernetes-charts.storage.googleapis.com/
          helm repo add elastic https://helm.elastic.co

      - name: Run chart-testing (lint)
        id: lint
        uses: docker://quay.io/helmpack/chart-testing:v3.0.0-beta.1
        with:
          entrypoint: sh -c
          args: |
            echo "Running `ct list-changed`..."
            
            changed=$(ct list-changed)
            
            if [ -z "$changed" ]; then
              echo "No chart changes detected."
              echo "::set-output name=changed::false"
            else
              echo "Detected chart changes."
              echo "::set-output name=changed::true"
            fi
            
            ct lint --debug

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          installLocalPathProvisioner: true
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: install
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
